### ISSUE TITLE
No readme present

### ISSUE THREAD

**Issue by Veerhan-glitch** [Veerhan-glitch/Projects_To_Do_List#2]
Create a valid and quality readme.md file for this repo.

**Comment by Coder-Manan** [comment]
@Veerhan-glitch Please review #4

**Comment by Coder-Manan** [comment]
@Veerhan-glitch  on Hacktoberfest website, it is showing that this repo is not participating in Hacktoberfest. Please add the Hacktoberfest Topic to the repo

**Comment by Veerhan-glitch** [comment]
done, sorry for the inconvenience.
