### ISSUE TITLE
No Projects.dat

### ISSUE THREAD

**Issue by Coder-Manan** [Veerhan-glitch/Projects_To_Do_List#3]
Currently the program looks for a `Projects.dat` file containing the required data, assuming that already a file exists.
A feature can be added so that the file is created in case someone runs the program for the first time on his/her computer.

**Comment by Coder-Manan** [comment]
@Veerhan-glitch please look if this feature can be added. I'll be happy to work on this! Also I would appreciate if `hacktoberfest` tag is added to the issue

**Comment by Veerhan-glitch** [comment]
Yes sure pls add that feature.

**Comment by Coder-Manan** [comment]
@Veerhan-glitch I think you have closed this by mistake. Please reopen it

**Comment by Veerhan-glitch** [comment]
oh my bad thanks for bringing it to my notice.

**Comment by Coder-Manan** [comment]
@Veerhan-glitch  pls review #5
