### ISSUE TITLE
No LICENSE file present in the repo

### ISSUE THREAD

**Issue by codeMehtab** [Veerhan-glitch/Projects_To_Do_List#7]
Hi @Veerhan-glitch there is no LICENSE.md file present in the repo, I would like to add one, if you feel thats needed please assign this issue to me to work on it.

**Comment by Veerhan-glitch** [comment]
Oh well can you pls explain me about license files?

**Comment by codeMehtab** [comment]
Sure, I have tried to give answers to these basic questions below:

**What is a Licence?**
_This is where you define who can use your project in their own. Means you are defining the list of permissions with which this project can be reused 
Most commonly used opensource licences are MIT, Apache, GPL, and BSD_

_An opensource Licence is needed to call a repo "opensource" so others can contribute or even reusue, wither for their own opensource projects or for their commercial projects
Some Licences restrice users to use it only for research and educational purpose (for students for their acadamics)_

**Why do you need a Licence to the github repository?**
_It is needed for the people to know how they can use this project in their work, in short what permissions are given to them, should they give mention or they can use it as completely free and opensource_

**Comment by Veerhan-glitch** [comment]
got it thx for the explanation.
alright i am assigning the issue to you.
while you are ate it it would be appreciated if you could also tell me the process of getting one (if it isn't simply just making a file)

**Comment by codeMehtab** [comment]
Yes this is very simple, the License I am adding is MIT opensource for the starting year 2022 and under name Veerhan. The performa text is available here: https://choosealicense.com/licenses/mit/#
I have raise a PR for this, please review and let me know of any applicable changes
[#8 ](https://github.com/Veerhan-glitch/Projects_To_Do_List/pull/8)

**Comment by codeMehtab** [comment]
Hi @Veerhan-glitch please merge this PR as well, added the link to Licese in this for the README:
[#10 ](https://github.com/Veerhan-glitch/Projects_To_Do_List/pull/10)

**Comment by Veerhan-glitch** [comment]
done
